# Generated by Django 5.1.4 on 2024-12-17 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('maintenance_date', models.DateField()),
                ('operational_status', models.CharField(choices=[('Running', 'Running'), ('Idle', 'Idle'), ('Faulty', 'Faulty')], max_length=10)),
                ('spare_parts_stock', models.PositiveIntegerField()),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SalesTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('payment_terms', models.CharField(choices=[('Netbanking', 'NetBanking'), ('Cash', 'Cash'), ('check', 'Check')], max_length=20)),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], max_length=20)),
                ('remarks', models.CharField(choices=[('Sale', 'Sale'), ('Purchase', 'Purchase')], max_length=10)),
            ],
            options={
                'verbose_name': 'Sales Table',
                'verbose_name_plural': 'Sales Tables',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_holder', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=15)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.position')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=100)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.material')),
            ],
        ),
    ]
